#!usr/bin/env ruby

def setup
  query = Elasticsearch::DSL::Search.search do
    query do
      regexp "fields.value" do
        value ".*(15061439).*"
      end
    end
  end

  response = Catalog::MARC::Record.search query

  response
end
